AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  smalruby3-aws-mesh-signaling-app

  WebRTC signaling application for Smalruby3 Mesh extension on AWS
  
Parameters:
  TableName:
    Type: String
    Default: 'smalruby_mesh_signaling_connections'
    Description: (Required) The name of the new DynamoDB to store connection identifiers for each connected clients. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: 'Required. Can be characters and underscore only. No numbers or special characters allowed.'

Resources:
  MeshSignalingWebSocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: Smalruby3 Mesh Signaling WebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref MeshSignalingWebSocket
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ConnectInteg
  ConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref MeshSignalingWebSocket
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnConnectFunction.Arn}/invocations
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref MeshSignalingWebSocket
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DisconnectInteg
  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref MeshSignalingWebSocket
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnDisconnectFunction.Arn}/invocations
  RegisterRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref MeshSignalingWebSocket
      RouteKey: register
      AuthorizationType: NONE
      OperationName: RegisterRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref RegisterInteg
  RegisterInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref MeshSignalingWebSocket
      Description: Send Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RegisterFunction.Arn}/invocations
  ListRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref MeshSignalingWebSocket
      RouteKey: list
      AuthorizationType: NONE
      OperationName: ListRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ListInteg
  ListInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref MeshSignalingWebSocket
      Description: Send Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListFunction.Arn}/invocations
  OfferRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref MeshSignalingWebSocket
      RouteKey: offer
      AuthorizationType: NONE
      OperationName: OfferRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref OfferInteg
  OfferInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref MeshSignalingWebSocket
      Description: Send Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OfferFunction.Arn}/invocations
  AnswerRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref MeshSignalingWebSocket
      RouteKey: answer
      AuthorizationType: NONE
      OperationName: AnswerRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref AnswerInteg
  AnswerInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref MeshSignalingWebSocket
      Description: Send Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AnswerFunction.Arn}/invocations
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - ConnectRoute
    - DisconnectRoute
    - RegisterRoute
    - ListRoute
    - OfferRoute
    - AnswerRoute
    Properties:
      ApiId: !Ref MeshSignalingWebSocket
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: dev
      Description: Development Stage
      DeploymentId: !Ref Deployment
      ApiId: !Ref MeshSignalingWebSocket
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: connectionId
        AttributeType: S
      - AttributeName: sourceIp
        AttributeType: S
      - AttributeName: isHost
        AttributeType: N
      - AttributeName: meshId
        AttributeType: S
      GlobalSecondaryIndexes:
      - IndexName: sourceIp-isHost-index
        KeySchema:
        - AttributeName: sourceIp
          KeyType: HASH
        - AttributeName: isHost
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
      - IndexName: meshId-index
        KeySchema:
        - AttributeName: meshId
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
      KeySchema:
      - AttributeName: connectionId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
      TableName: !Ref TableName
      TimeToLiveSpecification:
         AttributeName: ttl
         Enabled: True
  OnConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: onconnect/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TableName
  OnConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - MeshSignalingWebSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnConnectFunction
      Principal: apigateway.amazonaws.com
  OnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ondisconnect/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TableName
  OnDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - MeshSignalingWebSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnDisconnectFunction
      Principal: apigateway.amazonaws.com
  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: register/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TableName
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MeshSignalingWebSocket}/*'
  RegisterPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - MeshSignalingWebSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref RegisterFunction
      Principal: apigateway.amazonaws.com
  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: list/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TableName
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MeshSignalingWebSocket}/*'
  ListPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - MeshSignalingWebSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ListFunction
      Principal: apigateway.amazonaws.com
  OfferFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: offer/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TableName
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MeshSignalingWebSocket}/*'
  OfferPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - MeshSignalingWebSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OfferFunction
      Principal: apigateway.amazonaws.com
  AnswerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: answer/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref TableName
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MeshSignalingWebSocket}/*'
  AnswerPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - MeshSignalingWebSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AnswerFunction
      Principal: apigateway.amazonaws.com

Outputs:
  ConnectionsTableArn:
    Description: "Connections table ARN"
    Value: !GetAtt ConnectionsTable.Arn

  OnConnectFunctionArn:
    Description: "OnConnect function ARN"
    Value: !GetAtt OnConnectFunction.Arn

  OnDisconnectFunctionArn:
    Description: "OnDisconnect function ARN"
    Value: !GetAtt OnDisconnectFunction.Arn

  RegisterFunctionArn:
    Description: "Register ARN"
    Value: !GetAtt RegisterFunction.Arn

  ListFunctionArn:
    Description: "List ARN"
    Value: !GetAtt ListFunction.Arn

  OfferFunctionArn:
    Description: "Offer ARN"
    Value: !GetAtt OfferFunction.Arn

  AnswerFunctionArn:
    Description: "Answer ARN"
    Value: !GetAtt AnswerFunction.Arn

  WebSocketURI:
    Description: "The WSS Protocol URI to connect to"
    Value: !Join [ '', [ 'wss://', !Ref MeshSignalingWebSocket, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref 'Stage'] ]
